testify/config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index', as: :index

  #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ USER ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # method    path                      controller#action           alias
  get         'users/new',              to: 'users#new',            as: :new_user
  post        'users',                  to: 'users#create'
  get         'users/:id/edit',         to: 'users#edit',           as: :edit_user
  patch       'users/:id',              to: 'users#update',          as: :update_user
  get         'users/:id',              to: 'users#show',           as: :user
  delete      'users/:id',              to: 'users#destroy',         as: :destroy_user


  resources :testimonies, :except => :destroy do
    resources :comments, :except => :destroy
  end
  delete      'comments/:id',              to: 'comments#destroy',         as: :destroy_comment
  delete      'testimonies/:id',              to: 'testimonies#destroy',         as: :destroy_testimony

  # #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TESTIMONY ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # # method    path                      controller#action           alias
  #
  # get         'testimonies/index',           to: 'testimonies#index',        as: :index_testimony
  # get         'testimonies/new',              to: 'testimonies#new',            as: :new_testimony
  # post        'testimonies',                  to: 'testimonies#create',          as: :create_testimony
  # get         'testimonies/:id/edit',         to: 'testimonies#edit',           as: :edit_testimony
  # patch       'testimonies/:id',              to: 'testimonies#update',          as: :update_testimony
  # get         'testimonies/:id',              to: 'testimonies#show',           as: :testimony
  # delete      'testimonies/:id',              to: 'testimonies#destroy',         as: :destroy_testimony
  #
  # #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMMENT ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # # method    path                      controller#action           alias
  # get         'comments/new',              to: 'comments#new',            as: :new_comment
  # post        'comments',                  to: 'comments#create',          as: :create_comment
  # get         'comments/:id/edit',         to: 'comments#edit',           as: :edit_comment
  # patch       'comments/:id',              to: 'comments#update',          as: :update_comment
  # get         'comments/:id',              to: 'comments#show',           as: :comment
  # delete      'comments/:id',              to: 'comments#destroy',         as: :destroy_comment

  #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SESSION ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
    # method    path                      controller#action           alias
    get         '/login',                 to: 'sessions#new',         as: :login
    post        '/sessions',              to: 'sessions#create'
    get         '/logout',                to: 'sessions#destroy',      as: :logout

end

testify/app/models/user.rb
class User < ActiveRecord::Base
   require 'carrierwave'
    mount_uploader :avatar, AvatarUploader
    has_secure_password
     has_many :testimonies, dependent: :delete_all
     has_many :comments, dependent: :delete_all


    def self.confirm(params)
        @user = User.find_by(email: params[:email])
        @user.try(:authenticate, params[:password])
    end

    validates :first_name, :last_name, :email,
              presence: true,
              length: { maximum: 255 }, on: :create

    validates :email,
              uniqueness: true,
              format: {
                  with: /(.+)@(.+)/,
                  message: 'not a valid format'
              }, on: :create
end

testify/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def edit
        logged_in? @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if allowed?(@user.id) && @user.update(profile_params)
            flash[:notice] = 'Account successfully updated'
            redirect_to user_path
        else
            redirect_to user_path(@user)
            flash[:error] = 'You dont have access to this account'
        end
    end

    def create
        @user = User.create(user_params)
        login(@user)
        redirect_to @user
    end

    def show
        @user = User.find_by_id(params[:id])
        render :show
    end

    def destroy
        user = User.find_by_id(params[:id])
        if allowed?(user.id) && user.destroy
            flash[:notie] = 'Sorry to see you go. Account successfully deleted'
            redirect_to index_path
        else
            redirect_to user_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
    end

    def profile_params
        params.require(:user).permit(:first_name, :last_name,:username, :avatar, :email, :password)
    end
end

testify/app/helpers/users_helper.rb
module UsersHelper
end

testify/app/views/users/edit.html.erb
  <h4>Edit Profile</h4>
    <div class="row">
      <div class="col-xs-10">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :first_name %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :first_name, placeholder: "First Name" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :last_name %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :last_name, placeholder: "Last Name" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :username %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :username, placeholder: "Username" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :email %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :email, placeholder: "Email" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :avatar %>
            </div>
            <div class="col-sm-8">
              <%= f.file_field :avatar %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :submit %>
            </div>
            <div class="col-sm-8">
              <%= f.submit "Submit", class: "btn btn-primary" %>
              <%= link_to "Cancel", :back, class: "btn btn-default" %>
            </div>
          </div>
        <% end %>
        <hr />
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= link_to "Delete Account", user_path, class: "btn btn-danger", method: :delete %>
          </div>
        </div>
      </div>
    </div>

testify/app/views/users/new.html.erb
<center>
    <div id="forms">
        <div id="session_login">
            <div class="container">
                <h4>Sign Up</h4>
                <div class="row">
                    <div class="col-xs-10">

                        <%= form_for @user do |f| %>
                        <div>
                            <%= f.text_field :first_name, placeholder: "First Name" %>
                        </div>
                        <div>
                            <%= f.text_field :last_name, placeholder: "Last Name" %>
                        </div>
                        <div>
                            <%= f.text_field :email, placeholder: "Email" %>
                        </div>
                        <div>
                            <%= f.text_field :username, placeholder: "Username" %>
                        </div>
                        <div>
                            <%= f.password_field :password, placeholder: "Password" %>
                        </div>
                        <%= f.submit "Sign Up" %>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>
    </center>

testify/app/views/users/show.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner"></div>
    </div>
</header>

<section>
    <div id="user_show_cont" class="container">
        <!--beginning of profile section-->
        <div class="row">
            <div class="col-md-3 text-center">
                <div class="profile_pic">
                    <% if current_user.avatar.present? %>
                    <%= link_to image_tag(@user.avatar_url, :class => "img-circle center-block img-responsive"), user_path(current_user), :"data-no-turbolink" => true %>
                <% else %>
                    <%= link_to image_tag(('default.png').to_s, :class => "img-circle center-block img-responsive"), user_path(current_user), :"data-no-turbolink" => true %>
                    <% end %>
                </div>
                <p>
                    <br>
                    <b>First Name:</b>
                    <%= @user.first_name %>
                    <br>
                    <b>Last Name:</b>
                    <%= @user.last_name %>
                    <br>
                    <b>Username:</b>
                    <%= @user.username %>
                    <br>
                    <b>Joined:</b>
                    <%= @user.created_at.strftime("%-m-%-d-%Y") %>
                </p>
                <% allowed = allowed?(@user.id) %>
                <% if allowed %>
                <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %><br>
                <br>
                <%= link_to "Add Testimony", new_testimony_path, class: "btn btn-primary" %>
                <% end %>
            </div>
            <!--end of profile section-->
            <div class="col-md-1"></div>

            <div class="col-md-8">
                <div class="row text-center">
                    <h2 id="title_text">Testimonies</h2>
                </div>
                <div class="row" style="overflow:scroll; height:550px;">
                    <!--********LOOP THROUGH USER Testimony****************-->
                    <% @user.testimonies.each do |t| %>
                    <div class="card">
                        <h4>
                            <%= link_to "#{t.title}", testimony_path(t.id) %>
                        </h4>
                    </div>
                    <div class="card-content light-blue lighten-5">
                        <h5><%= t.verse %></h5>
                    </div>
                    <br>

                    <% end %>
                    <!--********CLOSE TESTIMONY LOOP****************-->
                </div>
            </div>
        </div>
    </div>
</section>