testify/config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index', as: :index

  #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ USER ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # method    path                      controller#action           alias
  get         'users/new',              to: 'users#new',            as: :new_user
  post        'users',                  to: 'users#create'
  get         'users/:id/edit',         to: 'users#edit',           as: :edit_user
  patch       'users/:id',              to: 'users#update',          as: :update_user
  get         'users/:id',              to: 'users#show',           as: :user
  delete      'users/:id',              to: 'users#destroy',         as: :destroy_user


  resources :testimonies, :except => :destroy do
    resources :comments, :except => :destroy
  end
  delete      'comments/:id',              to: 'comments#destroy',         as: :destroy_comment
  delete      'testimonies/:id',              to: 'testimonies#destroy',         as: :destroy_testimony

  # #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TESTIMONY ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # # method    path                      controller#action           alias
  #
  # get         'testimonies/index',           to: 'testimonies#index',        as: :index_testimony
  # get         'testimonies/new',              to: 'testimonies#new',            as: :new_testimony
  # post        'testimonies',                  to: 'testimonies#create',          as: :create_testimony
  # get         'testimonies/:id/edit',         to: 'testimonies#edit',           as: :edit_testimony
  # patch       'testimonies/:id',              to: 'testimonies#update',          as: :update_testimony
  # get         'testimonies/:id',              to: 'testimonies#show',           as: :testimony
  # delete      'testimonies/:id',              to: 'testimonies#destroy',         as: :destroy_testimony
  #
  # #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMMENT ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
  # # method    path                      controller#action           alias
  # get         'comments/new',              to: 'comments#new',            as: :new_comment
  # post        'comments',                  to: 'comments#create',          as: :create_comment
  # get         'comments/:id/edit',         to: 'comments#edit',           as: :edit_comment
  # patch       'comments/:id',              to: 'comments#update',          as: :update_comment
  # get         'comments/:id',              to: 'comments#show',           as: :comment
  # delete      'comments/:id',              to: 'comments#destroy',         as: :destroy_comment

  #!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SESSION ROUTES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#
    # method    path                      controller#action           alias
    get         '/login',                 to: 'sessions#new',         as: :login
    post        '/sessions',              to: 'sessions#create'
    get         '/logout',                to: 'sessions#destroy',      as: :logout

end

testify/app/models/testimony.rb
class Testimony < ActiveRecord::Base
  require 'carrierwave'
   mount_uploader :picture, PictureUploader
   mount_uploader :video, VideoUploader
   belongs_to :user
   has_many :comments, dependent: :destroy
   accepts_nested_attributes_for :comments, allow_destroy: true
end

testify/app/controllers/testimonies_controller.rb
class TestimoniesController < ApplicationController
    include HTTParty
    format :json

    before_action :setCurrentTestimony
    before_action :setCurrentUser

    def index
        @testimonies = Testimony.order('created_at DESC')
        @user = User.find_by_id(params[:id])
        render :index
    end

    def show
        @comment = Comment.find_by_id(params[:id])
          @testimony = Testimony.find_by_id(params[:id])
        render :show
    end

    def new
        if !params[:search].nil?
            @search = params[:search]
            # Use interpulation on refactor
            @testimonies = HTTParty.get('https://api.biblia.com/v1/bible/search/LEB.js?query=' + @search + '&mode=verse&start=0&limit=50&key=5f2273dfa89f32a2232474c83fac3921')
        else
            @testimonies = HTTParty.get('https://api.biblia.com/v1/bible/search/LEB.js?query=jesus&mode=verse&start=0&limit=50&key=5f2273dfa89f32a2232474c83fac3921')
        end
        @testimony = Testimony.new
    end

    def create
        @testimony = Testimony.new(testimony_params)
        @testimony.title = params[:testimony][:title]
        @testimony.verse = params[:testimony][:verse]
        @testimony.user_id = params[:testimony][:user_id]
        if @testimony.save
        redirect_to testimony_path(@testimony.id)
        else
            flash.now[:error] = @testimony.errors.full_messages.join(' , ')
            render :new
        end
    end

    def edit
      logged_in?(@testimony.user_id)
      @testimony = Testimony.find_by_id(params[:id])
    end

    def update
      if allowed?(@testimony.user_id)
      if @testimony.update(testimony_params)
        redirect_to testimony_path
      else
        flash[:error] = @testimony.errors.full_messages.join(" , ")
        render :edit
      end
    else
      redirect_to testimony_path
      end
    end

    def destroy
        @testimony = Testimony.find_by_id(params[:id])
        user_id = @testimony.user_id
        if allowed?(user_id)
            @testimony.destroy
            flash[:notice] = 'Testimony successfully deleted'
            redirect_to user_path(user_id)
        else
            flash[:error] = 'You dont have the proper cridentials to delete this post'
            redirect_to index_testimony_path
        end
    end

    private

    def testimony_params
    params.require(:testimony).permit(:title, :verse, :user_id, :picture, :video, :message)
    end

    def setCurrentTestimony
      @testimony = Testimony.find_by_id(params[:id])
    end

    def setCurrentUser
      @user = current_user
    end

end

testify/app/helpers/testimonies_helper.rb
module TestimoniesHelper
end

testify/app/views/testimonies/edit.html.erb
  <h4>Edit Profile</h4>
    <div class="row">
      <div class="col-xs-10">
        <%= form_for(@testimony, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :picture %>
            </div>
            <div class="col-sm-8">
              <%= f.file_field :picture %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :video %>
            </div>
            <div class="col-sm-8">
              <%= f.file_field :video %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :testify %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :message %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :submit %>
            </div>
            <div class="col-sm-8">
              <%= f.submit "Submit", class: "btn btn-primary" %>
              <%= link_to "Cancel", :back, class: "btn btn-default" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

testify/app/views/testimonies/index.html.erb
<div class="container-full">
    <div id="tm" class="container">
        <% @testimonies.each do |t| %>
        <div class="col-lg-12 col-md-12 col-xs-12 card">
            <div class="test_title">
                <%=link_to( image_tag(t.user.avatar, :class => "img-thumbnail center-block img-responsive", :id => "avi"), user_path(t.user.id)) %>
                <center>
                    <h4><%= link_to "#{t.title}", testimony_path(t.id) %></h2>
                    <div id="test_verse" class="test_verse light-blue lighten-5">
                        <p><%= t.verse %></p>
                    </div>
                    <span class="light-green lighten-5">
                        <%=t.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%I:%M%p")%></span>
                    <br>
                    <span class="light-green lighten-5">
                        <%= t.created_at.strftime("%-m-%-d-%Y") %></span>
                    <br>
                </center>
            </div>
            <br>
            <center>
                <div>
                    <b>View Testimony</b>
                </div>
                <span class="card-title activator grey-text text-darken-4">
                    <i class="material-icons">message</i>
                </span>
            </center>
            <div class="card-reveal">
                <span class="card-title grey-text text-darken-4"><%= t.user.first_name%>
                    <i class="material-icons right">close</i>
                </span><br>
                <center>
                <% if t.message.present? %>
                <p>" <%= t.message%> "</p>
                <% end %>
                <% if t.video.present? %>
                <%= video_tag(t.video, :size => "320x240", :controls => true)%>
                <% end %>
                <% if t.picture.present? %>
                <div>
                <%= image_tag(t.picture, :height => "240px") %>
              </div><br>
                <% end %>
                    <%= link_to "Leave a Comment", new_testimony_comment_path(t), class: "btn btn-danger", method: :get %>
                </center>
            </div>
        </div>
        <% end %>
    </div>
</div>

testify/app/views/testimonies/new.html.erb
<center>
    <div id="jumbotron_search" class="jumbotron img-responsive">
        <%= form_tag new_testimony_path, :method => 'get' do %>
        <p id="search_text" class="container">
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil, class: "btn" %>
        </p>
        <% end %>
    </div>
</center>
<center>
    <h1 id="title_text">Verses</h1>
</center>
<center>
    <div>
            <%if @testimonies["content-length"] != "0"%>
            <% @testimonies["results"].each_slice(3) do |ts| %>
            <div class="row">
              <% ts.each do |t| %>
                    <div class="card col-md-4">
                        <div class="card-image">
                            <% @title = t["title"] %>
                            <img src="https://images.unsplash.com/photo-1440407876336-62333a6f010f?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=aef01806defa8b0c87dd1243e2db2dba" class="img-responsive">
                            <span class="card-title"><%=@title%></span>
                        </div>

                        <div class="card-content light-blue lighten-5">
                            <%@verse = t["preview"]%>
                            <%=@verse.truncate(300)%>
                        </div>
                        <div class="card-action">
                            <% @user_id = current_user.id %>
                            <!-- Hidden Form -->
                            <%= form_for @testimony, url: {action: "create"} do |f| %>
                            <%= f.hidden_field :title, :value => @title %>
                            <%= f.hidden_field :verse, :value => @verse %>
                            <%= f.hidden_field :user_id, :value => @user_id %>
                            <%= button_tag(type: "submit", class: "btn") do %>
                            Save
                            <i class="glyphicon glyphicon-star"></i>
                            <% end %>
                            <% end %>
                            <!-- End Hidden Form -->
                        </div>
                    </div>&nbsp
                    <% end %>
            </div>
            <% end %>
            <% end %>
    </div>
  </center>

testify/app/views/testimonies/show.html.erb
<div class="row">
  <center>
    <div id="test_show" class="col-lg-6 col-md-6 col-xs-6  card text-center">
        <div class="card-action">
            <% allowed = allowed?(@testimony.user_id) %>
            <% if allowed %>
            <%= link_to 'Delete &nbsp <i class="material-icons">delete</i>'.html_safe, destroy_testimony_path, class: "btn btn-danger", method: :delete, data: {confirm: "Delete #{@testimony.title}?"} %>
            <%= link_to 'Testify &nbsp <i class="material-icons">edit</i>'.html_safe, edit_testimony_path, class: "btn btn-danger", method: :get %>
            <%= link_to 'Reply &nbsp <i class="material-icons">comment</i>'.html_safe, new_testimony_comment_path(@testimony), class: "btn btn-danger", method: :get %>
            <% else %>
            <%= link_to 'Leave a Comment &nbsp <i class="material-icons">comment</i>'.html_safe, new_testimony_comment_path(@testimony), class: "btn btn-danger", method: :get %>
            <% end %>
        </div>
        <div class="card-content light-blue lighten-5">
            <h3><%= @testimony.title %></h3><br>
            <h4><%= @testimony.verse %></h4>
        </div>
        <div class="card-image">
            <% if @testimony.video.present? %>
            <%= video_tag(@testimony.video, autoplay: :autoplay, loop: :loop, :size => "320x240", :controls => true)%>
            <% end %>
            <% if @testimony.picture.present? %>
            <div>
            <%= image_tag(@testimony.picture, :height => "320px", :width => "320px", :controls => true) %>
            </div>
            <% end %>
        </div>
        <div class="card-content">
            <p><%= @testimony.message %></p><br>
        </div>
    </div>
  </center>
  <div id="test_show" class="col-lg-6 col-md-6 col-xs-6" style="overflow:scroll; height:1050px;">
  <center>
  <% @testimony.comments.each do |c| %>
  <ul class="collection">
      <li class="collection-item avatar">
        <%=link_to( image_tag(c.user.avatar, :class => "img-thumbnail center-block img-responsive circle", :id => "avi"), user_path(c.user_id)) %>
        <span class="title"><%=c.user.first_name%></span><br>
        <p class="light-green lighten-5"> <%= c.comment %></p>

        <!-- for like count coming soon -->
        <!-- <a href="#!" class="secondary-content"><i class="material-icons">thumb_up</i></a> -->

      </li>
    </ul>
  <% end %>
 </center>
</div>
</div>